add_newline = true
format = """
$custom$directory$git_branch
󱞩 $character
"""

[custom.logo]
command = "echo "
when = "true"
style = "blue"
format = "[$output]($style) "
[character]
success_symbol = "[](green)"
error_symbol = "[✗](red)"
[directory]
style = "blue"     
truncation_length = 1
truncate_to_repo = false
format = "[$path/]($style) "
